/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalsystem;

import hospitalsystem.patterns1.AccessControlProxy;
import hospitalsystem.patterns1.DatabaseAdapter;  
import hospitalsystem.patterns1.User;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class ViewRecordsPage extends javax.swing.JFrame {

private void loadMedicalRecords() {
    try {
        DatabaseAdapter db = new DatabaseAdapter();
        List<Map<String, String>> records = db.select("MedicalRecords", null);
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Record_ID");
        model.addColumn("Patient");
        model.addColumn("Age");
        model.addColumn("Doctor");
        model.addColumn("Date");
        model.addColumn("Diagnosis");
        model.addColumn("Prescription");
        model.addColumn("Notes");
        

        for (Map<String, String> record : records) {
            Vector<String> row = new Vector<>();
            row.add(record.get("Record_ID"));
            row.add(record.get("Patient_Name"));
            row.add(record.get("Patient_Age"));
            row.add(record.get("Doctor_Name"));
            row.add(record.get("Date"));
            row.add(record.get("Diagnosis"));
            row.add(record.get("Prescription"));
            row.add(record.get("Notes"));
            model.addRow(row);
        }
        
        ViewAllMedicalRecordsTable.setModel(model);
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading records: " + ex.getMessage());
    }
}    

    private AccessControlProxy dataAccess;
    private User currentUser;

    public ViewRecordsPage(User currentUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.currentUser = currentUser;
        this.dataAccess = new AccessControlProxy(currentUser);
        
        applyPermissions();
        loadMedicalRecords();
        ViewAllMedicalRecordsTable.getColumnModel().getColumn(0).setCellEditor(null);
    }
    
    private void applyPermissions() {
        boolean canModify = currentUser.getRole().equals("Admin") || 
                           currentUser.getRole().equals("Doctor");
        
        UpdateButton.setEnabled(canModify);
        DeleteButton.setEnabled(canModify);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UpdateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewAllMedicalRecordsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(45, 101, 129));

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalsystem/Images & Icons/icons8-update-user-30.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noteworthy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalsystem/Images & Icons/icons8-medical-record-50.png"))); // NOI18N
        jLabel1.setText("View All Medical Records");

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalsystem/icons8-delete-32.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.setActionCommand("");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalsystem/Close.png"))); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        ViewAllMedicalRecordsTable.setFont(new java.awt.Font("Noteworthy", 1, 12)); // NOI18N
        ViewAllMedicalRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient", "Doctor", "Date", "Diagnosis", "Prescription", "Any Notes"
            }
        ));
        jScrollPane2.setViewportView(ViewAllMedicalRecordsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        if (ViewAllMedicalRecordsTable.isEditing()) {
    ViewAllMedicalRecordsTable.getCellEditor().stopCellEditing();
}
    int selectedRow = ViewAllMedicalRecordsTable.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a record to update");
        return;
    }
    
    try {
        DefaultTableModel model = (DefaultTableModel) ViewAllMedicalRecordsTable.getModel();
        
        String recordId = model.getValueAt(selectedRow, 0).toString();
        String patientName = model.getValueAt(selectedRow, 1).toString();
        String patientAge = model.getValueAt(selectedRow, 2).toString();
        String doctorName = model.getValueAt(selectedRow, 3).toString();
        String date = model.getValueAt(selectedRow, 4).toString();
        String diagnosis = model.getValueAt(selectedRow, 5).toString();
        String prescription = model.getValueAt(selectedRow, 6).toString();
        String notes = model.getValueAt(selectedRow, 7).toString();
        
        Map<String, String> updateData = new HashMap<>();
        updateData.put("Patient_Name", patientName);
        updateData.put("Patient_Age", patientAge);
        updateData.put("Doctor_Name", doctorName);
        updateData.put("Date", date);
        updateData.put("Diagnosis", diagnosis);
        updateData.put("Prescription", prescription);
        updateData.put("Notes", notes);
        
        boolean updated = dataAccess.updateData("MedicalRecords", 
                                                updateData, 
                                                "Record_ID = " + recordId);
        
        if (updated) {
            JOptionPane.showMessageDialog(this, 
                "Medical record updated successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            loadMedicalRecords(); 
        } else {
            JOptionPane.showMessageDialog(this, 
                "Update failed!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }


    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = ViewAllMedicalRecordsTable.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a record to delete");
        return;
    }
    
    try {
        String recordId = ViewAllMedicalRecordsTable.getValueAt(selectedRow, 0).toString();
        String patientName = ViewAllMedicalRecordsTable.getValueAt(selectedRow, 1).toString();
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this medical record?\n" +
            "Patient: " + patientName + "\n" +
            "Record ID: " + recordId + "\n\n" +
            "WARNING: This action cannot be undone!",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
               boolean deleted = dataAccess.deleteData("MedicalRecords", "Record_ID = " + recordId);
                
                if (deleted) {
                    JOptionPane.showMessageDialog(this, "Record deleted!");
                    loadMedicalRecords();
                } else {
                JOptionPane.showMessageDialog(this, "Delete failed!");
            }
        }
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewRecordsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewRecordsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewRecordsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewRecordsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewRecordsPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTable ViewAllMedicalRecordsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
